version: '3.8'

services:
  historical_data_extraction:
    build:
      context: .
      dockerfile: historical_extract/Dockerfile
    command: python -m src.main
    volumes:
      - ./historical_extract:/app

  daily_data_extraction:
    build:
      context: .
      dockerfile: daily_extract/Dockerfile
    command: python -m src.main
    volumes:
      - ./daily_extract:/app
